/**
 * Declare
 */
declare const ENV: string;
declare const URL_BASE_API_BINNACLE_AUDIT_BYREGISTRY_W:string;
declare const URL_BASE_API_BINNACLE_AUDIT_BYDATABASE_W:string;
declare const URL_BASE_API_BINNACLE_AUDIT_BYTABLE_W:string;

declare const URL_BASE_API_BINNACLE_LOGS_BYID_W:string;
declare const URL_BASE_API_BINNACLE_LOGS_BYDATERANGE_W:string;
declare const URL_BASE_API_BINNACLE_LOGS_BYTYPE_W:string;
declare const URL_BASE_API_BINNACLE_LOGS_BYUSER_W:string;

/**
 * Const
 */
const _ENV = ENV;
const _URL_BASE_API_BINNACLE_AUDIT_BYREGISTRY_W = URL_BASE_API_BINNACLE_AUDIT_BYREGISTRY_W;
const _URL_BASE_API_BINNACLE_AUDIT_BYDATABASE_W = URL_BASE_API_BINNACLE_AUDIT_BYDATABASE_W;
const _URL_BASE_API_BINNACLE_AUDIT_BYTABLE_W = URL_BASE_API_BINNACLE_AUDIT_BYTABLE_W;

const _URL_BASE_API_BINNACLE_LOGS_BYID_W = URL_BASE_API_BINNACLE_LOGS_BYID_W;
const _URL_BASE_API_BINNACLE_LOGS_BYDATERANGE_W = URL_BASE_API_BINNACLE_LOGS_BYDATERANGE_W;
const _URL_BASE_API_BINNACLE_LOGS_BYTYPE_W = URL_BASE_API_BINNACLE_LOGS_BYTYPE_W;
const _URL_BASE_API_BINNACLE_LOGS_BYUSER_W = URL_BASE_API_BINNACLE_LOGS_BYUSER_W;

/**
 * Export
 */
export {_ENV as ENV};
export {_URL_BASE_API_BINNACLE_AUDIT_BYREGISTRY_W as URL_BASE_API_BINNACLE_AUDIT_BYREGISTRY_W};
export {_URL_BASE_API_BINNACLE_AUDIT_BYDATABASE_W as URL_BASE_API_BINNACLE_AUDIT_BYDATABASE_W};
export {_URL_BASE_API_BINNACLE_AUDIT_BYTABLE_W as URL_BASE_API_BINNACLE_AUDIT_BYTABLE_W};

export {_URL_BASE_API_BINNACLE_LOGS_BYID_W as URL_BASE_API_BINNACLE_LOGS_BYID_W};
export {_URL_BASE_API_BINNACLE_LOGS_BYDATERANGE_W as URL_BASE_API_BINNACLE_LOGS_BYDATERANGE_W};
export {_URL_BASE_API_BINNACLE_LOGS_BYTYPE_W as URL_BASE_API_BINNACLE_LOGS_BYTYPE_W};
export {_URL_BASE_API_BINNACLE_LOGS_BYUSER_W as URL_BASE_API_BINNACLE_LOGS_BYUSER_W};